# Generated by Django 3.2 on 2021-07-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
